// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ContactController from "./contact_controller.js"
application.register("contact", ContactController)

import CoverPhotoUploadController from "./cover_photo_upload_controller.js"
application.register("cover-photo-upload", CoverPhotoUploadController)

import ParallaxHeaderController from "./parallax_header_controller.js"
application.register("parallax-header", ParallaxHeaderController)

import PostAttachmentController from "./post_attachment_controller.js"
application.register("post-attachment", PostAttachmentController)

import PostController from "./post_controller.js"
application.register("post", PostController)

import PostTitleController from "./post_title_controller.js"
application.register("post-title", PostTitleController)

import StickySidebarController from "./sticky_sidebar_controller.js"
application.register("sticky-sidebar", StickySidebarController)
