version: "3.9"

networks:
  default:
    external:
      name: digitalocean-apps_default

services:
  blog:
    container_name: blog
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 3000 -b '0.0.0.0'"
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: 'true'
      RAILS_LOG_TO_STDOUT: 'true'
    env_file:
    - .env.prod
    labels:
      - "traefik.http.routers.blog.rule=Host(`blog.20dots.com`)"
      # TODO: Move certResolver's name to ENV
      - "traefik.http.routers.whoami.tls.certResolver=dns-cloudflare"
      # Tell Traefik to use the port 3000 to connect to `web`
      - traefik.http.services.blog.loadbalancer.server.port=3000