services:
  web:
    build:
      context: .
      dockerfile: ops/docker/dev/Dockerfile
    init: true
    command: bash -c "bundle exec rails server -p 3000 -b '0.0.0.0'"
    environment:
      # Make it easy to use `rails credentials:edit`
      EDITOR: nano
    volumes:
      - .:/code
      # don't mount tmp directory
      - /code/tmp
    ports:
      - "3000:3000"
    labels:
      - "traefik.http.routers.20dots_web.rule=Host(`20dots.localhost`)"
      - "traefik.http.routers.20dots_web.entrypoints=web"
      # Tell Traefik to use the port 3000 to connect to `web`
      - traefik.http.services.20dots_web.loadbalancer.server.port=3000
    depends_on:
      - 'database'

  database:
    image: postgres:13.5-alpine3.15
    restart: always
    ports:
      # Make accessible on host on non-conflicting port
      - "5450:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

networks:
  default:
    name: traefik