
default: &default
  adapter: postgresql
  encoding: unicode
  host: database
  username: postgres
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: 20dots_development

test:
  <<: *default
  database: 20dots_development_test

production:
  database: 20dots_production
  username: 20dots
  password: <%= ENV['20DOTS_DATABASE_PASSWORD'] %>
