# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5ec968507377bb718d868dbb31d743cbcee6e2e463d680a95f17e892558d7f8f8fdfc86ae8795a00ed475777f9284f4a2d680f326c817d32c9385516bf9a605

test:
  secret_key_base: e698012be92271824a72c55170f001a34cd0f39212a3b3840f6d3fecc103d76f15f90f0c13be5fd9820182a4dc1da482aa375f865b379c2402aee6f0b01421c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
