---
- name: setup pre-requisites
  hosts: all
  become: true
  become_user: root
  roles:
    - configure-hosts-file

- name: install docker
  hosts: swarmservers
  roles:
    - docker-installation
  become: true
  become_user: root

# Install docker python package so we can use ansible helpers
- hosts: swarmservers
  become: true
  become_user: root
  tasks:
  - name: install pip3
    apt: name=python3-pip state=present

  - name: Install docker python package
    pip:
      name: docker

- name: add user to docker group
  hosts: swarmservers
  vars_files:
    - vars/default.yml
  roles:
    - add-user-to-docker-group

- name: initialize docker swarm
  hosts: swarm_managers
  roles:
    - docker-swarm-init

- hosts: "{{ lead_server }}"
  vars_files:
    - vars/default.yml
  tasks:
  - name: Create a network
    community.docker.docker_network:
      name: "{{ docker_network_name }}"
      driver: overlay

- hosts: "{{ lead_server }}"
  vars_files:
    - vars/default.yml
  tasks:
  - name: Add traefik label
    community.docker.docker_node:
      hostname: "{{ ansible_hostname }}"
      labels:
        "{{ docker_network_name }}.{{ docker_network_name }}-certificates": "true"
      labels_state: replace

- name: Add deployment key to authorized keys
  hosts: swarm_managers
  vars_files:
    - vars/default.yml
  roles:
    - add-deployment-ssh-key

- name: add workers to the swarm
  hosts: swarm_workers
  vars_files:
    - vars/default.yml
  roles:
    - docker-swarm-add-worker

- hosts: "{{ lead_server }}"
  vars_files:
    - vars/default.yml
    - vars/secrets.yml
  tasks:
  - name: Add docker secrets
    community.docker.docker_secret:
      name: "{{ item['name'] }}"
      data: "{{ item['value'] }}"
    with_items: "{{ docker_secrets }}"

