# Map host names between all nodes in the swarm
---
- name: Configure Hosts File
  lineinfile: path=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}}" state=present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: "{{ groups['swarmservers'] }}"

- name: Configure Hosts File vpc
  lineinfile: path=/etc/hosts regexp='.*{{ item }}-vpc$' line="{{ hostvars[item]['vpc_ip'] }} {{item}}-vpc" state=present
  with_items: "{{ groups['swarmservers'] }}"