---
user: vita
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/20dots.pub') }}"
sys_packages: [ 'curl', 'git', 'ufw']
vpc_ip: "10.108.0.0"
# In case we have more than one swarm manager
lead_server: "20dots-1"
docker_network_name: "traefik-public"