name: test suite
on: [push]

jobs:
  test-suite:
    name: Test Suite
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.2-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: 20dots_test
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: trust
        ports: ["5432:5432"]
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install packages
        run: |
          yarn install

      - name: Compile css assets
        run: |
          yarn build:css

      - name: Compile js assets
        run: |
          yarn build

      - name: Setup test database
        env:
          RAILS_ENV: test
          # postgres is running in container w/ 5432 bound on localhost
          DATABASE_URL: postgresql://postgres@localhost:5432/20dots_test
        run: |
          bin/rails db:create && bin/rails db:schema:load

      - name: Run tests
        env:
          DATABASE_URL: postgresql://postgres@localhost:5432/20dots_test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY_TEST }}
        run: bundle exec rspec
